### ISSUE TITLE
Retroarch dont start with files from this repo

### ISSUE THREAD

**Issue by git58** [willianholtz/Retroarch_ArchLinux#1]
Hello guys. I clone this repo to empty $HOME/.config/retroarch directory, but retroarch doesn't start...

**Comment by willianholtz** [comment]
The retroarch folder must be inside ./config. When cloning, the folder may have a different name. Make sure that when you download all the files, it looks like this.

![Screenshot_20240126_195353](https://github.com/willianholtz/Retroarch4Linux/assets/23488207/e0da3af2-2849-4100-b7d4-92ef1fa6a8fd)

**Comment by git58** [comment]
Same
![Screenshot_20240127_020057](https://github.com/willianholtz/Retroarch4Linux/assets/60933545/c6b912db-b03c-4ba0-a137-f3c76514e242)

**Comment by willianholtz** [comment]
Run retroarch through the terminal, and it sends the output error

**Comment by git58** [comment]
I already run it with terminal, and didn't get any message or error. Also I run it with -v flag and only get message of path to the retroarch config. The path to config is correct.

**Comment by willianholtz** [comment]
Try deleting the .config from the folder and run.

**Comment by git58** [comment]
I delete retroarch.cfg from $HOME/.config/retroarch/ folder and launch successfully
